In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, f1_score, recall_score, confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
df = pd.read_csv("Churn_treino.csv", sep=';')
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1         10134888       1
1             608     Spain  Female  ...               1         11254258       0
2             502    France  Female  ...               0         11393157       1
3             699    France  Female  ...               0          9382663       0
4             850     Spain  Female  ...               1           790841       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0          9627064       0
9996          516    France    Male  ...               1         10169977       0
9997          709    France  Female  ...               1          4208558       1
9998          772   Germany    Male  ...               0          9288852       1
9999          792    France  Female  ...               0          3819078       0

[10000 rows x 11 columns]

In [ ]:
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [ ]:
X

      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1         10134888
1             608     Spain  Female  ...          0               1         11254258
2             502    France  Female  ...          1               0         11393157
3             699    France  Female  ...          0               0          9382663
4             850     Spain  Female  ...          1               1           790841
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0          9627064
9996          516    France    Male  ...          1               1         10169977
9997          709    France  Female  ...          0               1          4208558
9998          772   Germany    Male  ...          1               0          9288852
9999          792    France  Female  ...          1               0          3819078

[10000 rows x 10 columns]

In [ ]:
standardscaler = StandardScaler()
numerical = X.select_dtypes(include=['int64', 'float64']).columns
X[numerical] = standardscaler.fit_transform(X[numerical])

In [ ]:
X

      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0       -0.326221    France  Female  ...   0.646092        0.970243         0.170614
1       -0.440036     Spain  Female  ...  -1.547768        0.970243         0.353281
2       -1.536794    France  Female  ...   0.646092       -1.030670         0.375948
3        0.501521    France  Female  ...  -1.547768       -1.030670         0.047859
4        2.063884     Spain  Female  ...   0.646092        0.970243        -1.354223
...           ...       ...     ...  ...        ...             ...              ...
9995     1.246488    France    Male  ...   0.646092       -1.030670         0.087743
9996    -1.391939    France    Male  ...   0.646092        0.970243         0.176340
9997     0.604988    France  Female  ...  -1.547768        0.970243        -0.796492
9998     1.256835   Germany    Male  ...   0.646092       -1.030670         0.032551
9999     1.463771    France  Female  ...   0.646092       -1.030670        -0.860051

[10000 rows x 10 columns]

In [ ]:
labelencoder = LabelEncoder()
categorical = X.select_dtypes(include='object').columns
for col in categorical:
  X[col] = labelencoder.fit_transform(X[col])

In [ ]:
X

      CreditScore  Geography  ...  IsActiveMember  EstimatedSalary
0       -0.326221          0  ...        0.970243         0.170614
1       -0.440036          2  ...        0.970243         0.353281
2       -1.536794          0  ...       -1.030670         0.375948
3        0.501521          0  ...       -1.030670         0.047859
4        2.063884          2  ...        0.970243        -1.354223
...           ...        ...  ...             ...              ...
9995     1.246488          0  ...       -1.030670         0.087743
9996    -1.391939          0  ...        0.970243         0.176340
9997     0.604988          0  ...        0.970243        -0.796492
9998     1.256835          1  ...       -1.030670         0.032551
9999     1.463771          0  ...       -1.030670        -0.860051

[10000 rows x 10 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=0
)

In [ ]:
modelo = Sequential()

In [ ]:
modelo.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=32, activation='relu'))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=64, activation='relu'))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=1, activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
modelo.fit(X_train, y_train, epochs=50, batch_size=32)

Epoch 1/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7901 - loss: 0.5048
Epoch 2/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7977 - loss: 0.4618
Epoch 3/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8011 - loss: 0.4419
Epoch 4/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8063 - loss: 0.4325
Epoch 5/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8194 - loss: 0.4215
Epoch 6/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8259 - loss: 0.4089
Epoch 7/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8273 - loss: 0.4036
Epoch 8/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8341 - loss: 0.3991
Epoch 9/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8390 - loss: 0.3876
Epoch 10/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3860
Epoch 11/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8400 - loss: 0.3870
Epoch 12/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8409 - loss: 0.3886
Epoch 13/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8453 - loss: 0.3807
Epoch 14/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8437 - loss: 0.3770
Epoch 15/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8474 - loss: 0.3797
Epoch 16/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8470 - loss: 0.3707
Epoch 17/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8480 - loss: 0.3761
Epoch 18/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8441 - loss: 0.3728
Epoch 19/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8487 - loss: 0.3712
Epoch 20/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8479 - loss: 0.3706
Epoch 21/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8531 - loss: 0.3691
Epoch 22/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8534 - loss: 0.3646
Epoch 23/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8526 - loss: 0.3672
Epoch 24/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8524 - loss: 0.3619
Epoch 25/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8523 - loss: 0.3641
Epoch 26/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8504 - loss: 0.3633
Epoch 27/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8544 - loss: 0.3645
Epoch 28/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8540 - loss: 0.3635
Epoch 29/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8534 - loss: 0.3620
Epoch 30/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8559 - loss: 0.3593
Epoch 31/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8523 - loss: 0.3575
Epoch 32/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8526 - loss: 0.3607
Epoch 33/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8529 - loss: 0.3619
Epoch 34/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8521 - loss: 0.3609
Epoch 35/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8486 - loss: 0.3600
Epoch 36/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8556 - loss: 0.3578
Epoch 37/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8554 - loss: 0.3575
Epoch 38/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8540 - loss: 0.3550
Epoch 39/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8583 - loss: 0.3559
Epoch 40/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8577 - loss: 0.3577
Epoch 41/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8554 - loss: 0.3550
Epoch 42/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8554 - loss: 0.3572
Epoch 43/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8556 - loss: 0.3541
Epoch 44/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3542
Epoch 45/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3539
Epoch 46/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3499
Epoch 47/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8571 - loss: 0.3529
Epoch 48/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8591 - loss: 0.3513
Epoch 49/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8580 - loss: 0.3516
Epoch 50/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8567 - loss: 0.3524

In [ ]:
previsoes = modelo.predict(X_test)
previsoes

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.35393173],
       [0.260301  ],
       [0.20858216],
       ...,
       [0.09211686],
       [0.10830753],
       [0.4839154 ]], dtype=float32)

In [ ]:
y_pred = (previsoes > 0.5).astype('int32')
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [ ]:
print(f"Acurácia: {accuracy_score(y_test, y_pred)}")
print(f"F1: {f1_score(y_test, y_pred)}")
print(f"Recall: {recall_score(y_test, y_pred)}")
print(f"Matriz de Confusão: {confusion_matrix(y_test, y_pred)}")

Acurácia: 0.8616666666666667
F1: 0.5803842264914054
Recall: 0.46215780998389694
Matriz de Confusão: [[2298   81]
 [ 334  287]]